openapi: 3.0.3
info:
  title: Todo List ASP.NET Web API
  description: For more information see https://github.com/DanielNieuwoudt/developer-assessment.git
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
security:
  - bearerAuth: [ ]
paths:
  /TodoItems/{id}:
    get:
      tags:
        - TodoItems
      operationId: getTodoItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/NotFound"
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

    put:
      tags:
        - TodoItems
      operationId: putTodoItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/TodoItem'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/NotFound"
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /TodoItems:
    get:
      tags:
        - TodoItems
      operationId: getTodoItems
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItems'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

    post:
      tags:
        - TodoItems
      operationId: postTodoItem
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/TodoItem'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BadRequest:
      type: object
      properties:
        title:
          type: string
          description: Summary of why the request failed.
        type:
          type: string
          description: URI reference that identifies the error type.
        status:
          type: integer
          description: The HTTP code.
        errors:
          type: object
          description: Collection of validation failures.
          additionalProperties:
            type: array
            items:
              type: string
        traceId:
          type: string
          description: Request identifier for support purposes.  
      additionalProperties: false
      example:
        title: "One or more validation errors occurred."
        type: "https://tools.ietf.org/html/rfc7231#section-6.5.1"
        status: "400"
        errors:
          name:
            - "Id"
            - "Id can not be empty"
        traceId: "00-abc123456789def-ghi987654321jkl-01"
    NotFound:
      type: object
      properties:
        title:
          type: string
          description: Summary of why the request failed.
        type:
          type: string
          description: URI reference that identifies the error type.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        status:
          type: integer
          description: The HTTP code.
        traceId:
          type: string
          description: Request identifier for support purposes.
      additionalProperties: false
      example:
        title: "The specified resource was not found."
        type: "https://tools.ietf.org/html/rfc7231#section-6.5.4"
        status: "404"
        traceId: "00-abc123456789def-ghi987654321jkl-01"          
    InternalServerError:
      type: object
      properties:
        title:
          type: string
          description: Summary of why the request failed.
        type:
          type: string
          description: URI reference that identifies the error type.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        status:
          type: integer
          description: The HTTP code.
        traceId:
          type: string
          description: Request identifier for support purposes.
      additionalProperties: false
      example:
        title: "An error occurred while processing your request."
        type: "https://tools.ietf.org/html/rfc7231#section-6.6.1"
        status: "500"
        traceId: "00-abc123456789def-ghi987654321jkl-01"          
    TodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        isCompleted:
          type: boolean
      additionalProperties: false
    TodoItems:
      type: array
      items:
        $ref: '#/components/schemas/TodoItem'
