name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup-docker:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

  build-services:
    runs-on: ubuntu-latest
    needs: [checkout, setup-docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build services
        run: docker compose -f docker-compose-tests.yaml build

  run-services:
    runs-on: ubuntu-latest
    needs: build-services

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run services
        run: docker compose -f docker-compose.yaml up -d

  run-tests:
    runs-on: ubuntu-latest
    needs: run-services

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: docker compose -f docker-compose-tests.yaml run contracts

  teardown:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tear down services
        if: always()
        run: docker compose -f docker-compose-tests.yaml down
